### PR TITLE
Ka 2018 06 update fontawesome

### PR DESCRIPTION
**Pull request by fuzzylogic2000**

### CODE REVIEW

**Comment by fuzzylogic2000** [comment]
Works with: https://github.com/liqd/adhocracy4/pull/269
Please test in all projects, merge a4, upgrade a4 and merge here!

**Comment by fuzzylogic2000** [comment]
Well, not working with the current a4! The polls somehow need something else, which we need to check.

**Comment by fuzzylogic2000** [comment]
@ihucos I don't get AE to work with the new polls in A4. Because:

`ERROR in ./node_modules/adhocracy4/adhocracy4/polls/static/polls/PollManagement.jsx
Module not found: Error: Can't resolve 'react-flip-move' in '/home/katharina/a4-advocate-europe/node_modules/adhocracy4/adhocracy4/polls/static/polls'
 @ ./node_modules/adhocracy4/adhocracy4/polls/static/polls/PollManagement.jsx 18:15-41
 @ ./node_modules/adhocracy4/adhocracy4/polls/static/polls/react_polls.jsx
 @ ./node_modules/adhocracy4/index.js
 @ ./advocate_europe/assets/js/app.js
 @ multi ./advocate_europe/assets/scss/all.scss ./advocate_europe/assets/js/app.js

ERROR in ./node_modules/adhocracy4/adhocracy4/polls/static/polls/QuestionForm.jsx
Module not found: Error: Can't resolve 'react-flip-move' in '/home/katharina/a4-advocate-europe/node_modules/adhocracy4/adhocracy4/polls/static/polls'
 @ ./node_modules/adhocracy4/adhocracy4/polls/static/polls/QuestionForm.jsx 5:15-41
 @ ./node_modules/adhocracy4/adhocracy4/polls/static/polls/PollManagement.jsx
 @ ./node_modules/adhocracy4/adhocracy4/polls/static/polls/react_polls.jsx
 @ ./node_modules/adhocracy4/index.js
 @ ./advocate_europe/assets/js/app.js
 @ multi ./advocate_europe/assets/scss/all.scss ./advocate_europe/assets/js/app.js
`

And I just can't find the fix. I tried adding the polls app and also adding the reactPolls globally to apps.js. Could you check?

**Comment by fuzzylogic2000** [comment]
@MagdaN Help!

**Comment by MagdaN** [comment]
@fuzzylogic2000 the polls depend on react-flip-moves, so they need to be installed, even though the poll code is not going to be delivered to our FE (I think)

**Pull request merged**
