### PR TITLE
Introducing fallback image for ideas and blog posts

### LINKED ISSUE #318: Provide proper fallback image for ideas

### PR DESCRIPTION
**Pull request by mkind**
* fixes #318.

### CODE REVIEW

**Comment by MagdaN** [comment]
@mkind I used the blue fallback image for ideas because the first blogpost in the blogpost overlaps with the blue top bar in the blog index view. The blue of the top bar is the same blue as the one in the fallback image and therefore did not look too good. Therefore I had to use the yellow one for blogposts and the blue ones for ideas.

**Comment by mkind** [comment]
@MagdaN Ok

**Review by fuzzylogic2000 — APPROVED** [review]
See gif.

**Pull request merged**
