### PR TITLE
introducing first CSP version

### PR DESCRIPTION
**Pull request by mkind**
* introducing CSP
* blocked by issue https://github.com/liqd/a4-advocate-europe/issues/624

### CODE REVIEW

**Comment by slomo** [comment]
The language setting has been replaced by document lang: https://github.com/liqd/a4-opin/commit/c823589281d4fdb3bbec3ea6a7896579808b4d25#diff-08aeaf2ec5940faaaee5ba7323613142

We could either do the same here or remove it completely since, because we don't need it anymore anyhow.

**Comment by slomo** [comment]
I removed the script and did some initial testing:

 1. our dev setup uses unsafe eval, due to eval based source maps for webpack (see my work arround)
 2. there are a lot of csp violations from wagtail admin with the current setup so that it doesn't work

To fix the second issue, we can either exclude the wagtail urls, all tough it is not recommend or try to apply a weaker policy with some decorator to the wagtail view.

**Comment by mkind** [comment]
Good point. I'll look at the second issue.

**Comment by mkind** [comment]
@slomo the most secure way would be to add the wagtail scripts via hash. My point is, that it is a big point to weaken the security policy for an admin interface.

**Comment by slomo** [comment]
Even if that would be possible, it will certainly break on most updates. Possibly leading to the CSP being disabled in the future.

So I guess the best solution would be running the wagtail admin under a different domain. But I am not sure if that is even possible. And while it certainly would be do able in our own infrastructure, it would for sure not work on platform.sh or heroku.

The second best for me is to apply less strict rules for everything under `/wagtail`, which being on the domain is questionable. But it is the only way I see, where we could start adapting a CSP. Which would unfortunately be quite lax at the moment.

**Comment by slomo** [comment]
As usual we are not the first https://github.com/wagtail/wagtail/issues/1288

Just another idea: We might try to convince/help wagtail with getting rid of their inline scripts. There is already a PR for disabling gravatar (https://github.com/wagtail/wagtail/pull/4062) and since they rewrite the editor component (from hallo.js to drafttailhttps://github.com/wagtail/wagtail/pull/4136 ) while apparently switching to react, they might also remove the eval.

Magda mentioned once that they have a quite active mailing list / google group where we could address this.

**Comment by rmader** [comment]
We manage that in the config now

**Pull request closed without merging**
