### PR TITLE
add dates to idea views

### LINKED ISSUE #386: project year should be added to the idea space list and detail views
design in zeplin!

### PR DESCRIPTION
**Pull request by fuzzylogic2000**
fixes #386

### CODE REVIEW

**Review by mkind — COMMENTED** [review]
The design requires a space of 12px between every item?

**Comment by fuzzylogic2000** [comment]
Which item? For the list, I used the styling that was there. And for the detail view I also didn't change the styling and just checked that colour and font size were right. What did I miss?

**Comment by fuzzylogic2000** [comment]
Ah, I see. Will add that!

**Comment by fuzzylogic2000** [comment]
There it is! I only added 10px, because otherwise three-digit likes and comment counts didn't fit.

**Comment by mkind** [comment]
Looks good

**Pull request merged**
