### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by rmader**
See commits. Mostly things that we just did in other projects.

### CODE REVIEW

**Comment by rmader** [comment]
Hm, don't understand the error. @fuzzylogic2000 or @MagdaN, do you have an idea?

**Comment by fuzzylogic2000** [comment]
That's strange! It still works on the real side: The user is allowed to add an idea sketch during the IdeaSketchPhase. And it works for all other permissions.

**Comment by fuzzylogic2000** [comment]
@MagdaN Did you solve the mistery?

**Comment by rmader** [comment]
Solved in ec23ff115c33d24372183d5e40e149cef403185d. The problem was that since https://github.com/liqd/adhocracy4/commit/3b60590a8eee3e67f7288f98c62fa795c373610b `active_phase` is a cached property, so it wouldn't change within a single test instance. Fixed by moving those two tests out into their own test instances.

**Comment by fuzzylogic2000** [comment]
Ahhh! Very nice!

**Pull request merged**
